export const ZURICH_MUNICIPALITIES = [
  "Adliswil",
  "Aesch",
  "Aeugst am Albis",
  "Affoltern am Albis",
  "Altikon",
  "Andelfingen",
  "Bachenbülach",
  "Bachs",
  "Bassersdorf",
  "Bauma",
  "Benken",
  "Berg am Irchel",
  "Birmensdorf",
  "Bonstetten",
  "Boppelsen",
  "Brütten",
  "Bubikon",
  "Buch am Irchel",
  "Buchs",
  "Bäretswil",
  "Bülach",
  "Dachsen",
  "Dielsdorf",
  "Dietikon",
  "Dietlikon",
  "Dinhard",
  "Dorf",
  "Dägerlen",
  "Dällikon",
  "Dänikon",
  "Dättlikon",
  "Dübendorf",
  "Dürnten",
  "Egg",
  "Eglisau",
  "Elgg",
  "Ellikon an der Thur",
  "Elsau",
  "Embrach",
  "Erlenbach",
  "Fehraltorf",
  "Feuerthalen",
  "Fischenthal",
  "Flaach",
  "Flurlingen",
  "Freienstein-Teufen",
  "Fällanden",
  "Geroldswil",
  "Glattfelden",
  "Gossau",
  "Greifensee",
  "Grüningen",
  "Hagenbuch",
  "Hausen am Albis",
  "Hedingen",
  "Henggart",
  "Herrliberg",
  "Hettlingen",
  "Hinwil",
  "Hittnau",
  "Hochfelden",
  "Hombrechtikon",
  "Horgen",
  "Höri",
  "Hüntwangen",
  "Hüttikon",
  "Illnau-Effretikon",
  "Kappel am Albis",
  "Kilchberg",
  "Kleinandelfingen",
  "Kloten",
  "Knonau",
  "Küsnacht",
  "Langnau am Albis",
  "Laufen-Uhwiesen",
  "Lindau",
  "Lufingen",
  "Marthalen",
  "Maschwanden",
  "Maur",
  "Meilen",
  "Mettmenstetten",
  "Männedorf",
  "Mönchaltorf",
  "Neerach",
  "Neftenbach",
  "Niederglatt",
  "Niederhasli",
  "Niederweningen",
  "Nürensdorf",
  "Oberembrach",
  "Oberengstringen",
  "Oberglatt",
  "Oberrieden",
  "Oberweningen",
  "Obfelden",
  "Oetwil am See",
  "Oetwil an der Limmat",
  "Opfikon",
  "Ossingen",
  "Otelfingen",
  "Ottenbach",
  "Pfungen",
  "Pfäffikon",
  "Rafz",
  "Regensberg",
  "Regensdorf",
  "Rheinau",
  "Richterswil",
  "Rickenbach",
  "Rifferswil",
  "Rorbas",
  "Russikon",
  "Rümlang",
  "Rüschlikon",
  "Rüti",
  "Schlatt",
  "Schleinikon",
  "Schlieren",
  "Schwerzenbach",
  "Schöfflisdorf",
  "Seegräben",
  "Seuzach",
  "Stadel",
  "Stallikon",
  "Stammheim",
  "Steinmaur",
  "Stäfa",
  "Thalheim an der Thur",
  "Thalwil",
  "Truttikon",
  "Trüllikon",
  "Turbenthal",
  "Uetikon am See",
  "Uitikon",
  "Unterengstringen",
  "Urdorf",
  "Uster",
  "Volken",
  "Volketswil",
  "Wald",
  "Wallisellen",
  "Wangen-Brüttisellen",
  "Wasterkingen",
  "Weiach",
  "Weiningen",
  "Weisslingen",
  "Wettswil am Albis",
  "Wetzikon",
  "Wiesendangen",
  "Wil",
  "Wila",
  "Wildberg",
  "Winkel",
  "Winterthur",
  "Wädenswil",
  "Zell",
  "Zollikon",
  "Zumikon",
  "Zürich"
] as const;

export const ZURICH_LOCALITY_ALIASES: Record<string, string> = {
  "Aathal-Seegräben": "Seegräben",
  "Brüttisellen": "Wangen-Brüttisellen",
  Effretikon: "Illnau-Effretikon",
  Freienstein: "Freienstein-Teufen",
  Glattbrugg: "Opfikon",
  Rikon: "Zell",
  "Rutschwil (Dägerlen)": "Dägerlen",
  Unterstammheim: "Stammheim",
  "Wil ZH": "Wil"
} as const;
